[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlflow>=3.1.4",
    "pip>=25.1.1",
    "seaborn>=0.13.2",
    "zenml[mlflow,server]>=0.84.0",
]
